# Generated by Django 4.1.3 on 2024-01-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('images', models.JSONField(blank=True, null=True)),
                ('address', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('amenities', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=75)),
                ('bio', models.CharField(max_length=100)),
            ],
        ),
    ]
