# Generated by Django 4.1.3 on 2024-01-31 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackHotelBookingapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField(blank=True, null=True)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('price_per_night', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackHotelBookingapi.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(null=True)),
                ('no_of_guests', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackHotelBookingapi.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackHotelBookingapi.user')),
            ],
        ),
    ]
